filter:
    paths: ['library/Nestedset/*']
    excluded_paths: ['tests/*']

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [tests]
    php_cpd:
        enabled: true
        excluded_dirs: [tests]
