language: php
php:
  - 5.5
  - 5.4
before_script:
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  - wget https://packages.zendframework.com/releases/ZendFramework-1.12.7/ZendFramework-1.12.7-minimal.tar.gz
  - tar -xzf ZendFramework-1.12.7-minimal.tar.gz
  - ln -s ../ZendFramework-1.12.7-minimal/library/Zend/ library/
script:
  ## Atoum
  - php mageekguy.atoum.phar -d tests/
after_script:
  ## Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
