language: php
php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
branches:
  only:
    - master
addons:
  code_climate:
    repo_token:
      secure: "WKOU1lou2JCzy/YZH8YxTyN90EqlieQWgzUhWpj0p71KhlXwJQ/Seq6SSA0vKHpeeLinuaZBGoX4DuGrqkbi0s6kGHNP02cycMFuu1tY2E69CNX8OKz5D5Vv3cXjgzpaRTtyfRkxfGzxogorYPivrCchV1wrtMc6ERB/dE0pWFo="
before_script:
  - wget https://packages.zendframework.com/releases/ZendFramework-1.12.7/ZendFramework-1.12.7-minimal.tar.gz
  - tar -xzf ZendFramework-1.12.7-minimal.tar.gz
  - ln -s ../ZendFramework-1.12.7-minimal/library/Zend/ library/
  - composer install --dev
script:
  - phpunit
after_script:
  ## Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
  ## Code Climate
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -v -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
